#include <jni.h>
#include <openssl/sha.h> // The native cryptographic library header
#include "CryptoHash.h"  // Automatically generated by javac -h

/*
 * Class:     CryptoHash
 * Method:    computeSHA256
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CryptoHash_computeSHA256
  (JNIEnv *env, jobject thisObj, jbyteArray inputData) {

    // 1. Get the length of the input data
    jsize length = (*env)->GetArrayLength(env, inputData);

    // 2. Obtain a pointer to the input elements in native memory
    jbyte *data = (*env)->GetByteArrayElements(env, inputData, NULL);

    // 3. Prepare a buffer for the SHA-256 hash (always 32 bytes / 256 bits)
    unsigned char hashBuffer[SHA256_DIGEST_LENGTH];

    // 4. Perform the hash computation using OpenSSL's libcrypto
    SHA256((unsigned char*)data, length, hashBuffer);

    // 5. Release the input array elements (JNI_ABORT = do not copy changes back)
    (*env)->ReleaseByteArrayElements(env, inputData, data, JNI_ABORT);

    // 6. Create a new byte array in the JVM for our resulting hash
    jbyteArray result = (*env)->NewByteArray(env, SHA256_DIGEST_LENGTH);

    // 7. Copy our natively computed hash into the Java result array
    (*env)->SetByteArrayRegion(env, result, 0, SHA256_DIGEST_LENGTH, (jbyte*)hashBuffer);

    // 8. Return the hash array back to Java
    return result;
}