#include <jni.h>
#include <string.h>
#include <stdlib.h>
#include "ConfigParser.h" // Generated by javac

/*
 * Class:     ConfigParser
 * Method:    parseConfig
 * Signature: (Ljava/lang/String;[I)LConfigParser$ConfigResult;
 */
JNIEXPORT jobject JNICALL Java_ConfigParser_parseConfig(JNIEnv *env, jobject obj, jstring rawConfig, jintArray limits) {
    if (rawConfig == NULL || limits == NULL) {
        return NULL;
    }

    // --- 1. Read and parse the raw configuration string ---
    const char *c_str = (*env)->GetStringUTFChars(env, rawConfig, NULL);
    if (c_str == NULL) return NULL;

    // Create a mutable copy of the string for tokenization
    size_t len = strlen(c_str);
    char *config_copy = (char *)malloc(len + 1);
    strcpy(config_copy, c_str);

    // Default parsed values
    char parsed_host[256] = "localhost";
    int parsed_port = 80;
    int parsed_timeout = 30;

    // Tokenize the string by ';' to get "key=value" pairs
    char *token = strtok(config_copy, ";");
    while (token != NULL) {
        // Find the '=' delimiter for key/value separation
        char *eq_ptr = strchr(token, '=');
        if (eq_ptr != NULL) {
            *eq_ptr = '\0'; // Split the string into key and value
            char *key = token;
            char *value = eq_ptr + 1;

            // Operate on the configuration content
            if (strcmp(key, "host") == 0) {
                strncpy(parsed_host, value, sizeof(parsed_host) - 1);
                parsed_host[sizeof(parsed_host) - 1] = '\0';
            } else if (strcmp(key, "port") == 0) {
                parsed_port = atoi(value);
            } else if (strcmp(key, "timeout") == 0) {
                parsed_timeout = atoi(value);
            }
        }
        token = strtok(NULL, ";");
    }

    // Clean up string parsing memory
    free(config_copy);
    (*env)->ReleaseStringUTFChars(env, rawConfig, c_str);

    // --- 2. Read the primitive integer array ---
    jsize limits_len = (*env)->GetArrayLength(env, limits);
    int max_retries = 3;      // Default
    int max_connections = 10; // Default
    
    if (limits_len >= 2) {
        jint *limits_arr = (*env)->GetIntArrayElements(env, limits, NULL);
        max_retries = limits_arr[0];
        max_connections = limits_arr[1];
        // Release array memory (JNI_ABORT means we didn't alter it, no need to copy back)
        (*env)->ReleaseIntArrayElements(env, limits, limits_arr, JNI_ABORT);
    }

    // --- 3. Format into a usable Java object (ConfigResult) ---
    // Find the ConfigResult nested class
    jclass resultClass = (*env)->FindClass(env, "ConfigParser$ConfigResult");
    if (resultClass == NULL) return NULL;

    // Find the constructor ID: (String, int, int, int, int)
    jmethodID constructor = (*env)->GetMethodID(env, resultClass, "<init>", "(Ljava/lang/String;IIII)V");
    if (constructor == NULL) return NULL;

    // Convert the parsed C host string back into a Java String
    jstring jHost = (*env)->NewStringUTF(env, parsed_host);

    // Instantiate the ConfigResult object
    jobject resultObj = (*env)->NewObject(env, resultClass, constructor, 
                                          jHost, parsed_port, parsed_timeout, 
                                          max_retries, max_connections);

    // --- 4. Return the parsed output to Java ---
    return resultObj;
}