/**
 * Exposes the native C++ data-transformation pipeline to Java.
 *
 * <h2>Pipeline Stages</h2>
 * <ol>
 *   <li><b>Read</b>   – {@link #nativeRead}      : interprets the low-level input format</li>
 *   <li><b>Transform</b> – {@link #nativeTransform}: applies transformation rules</li>
 *   <li><b>Generate</b>  – {@link #nativeGenerate} : produces the final output</li>
 * </ol>
 *
 * <h2>Thread Safety</h2>
 * Each call to {@link #execute} is stateless from Java's perspective.
 * Thread safety within the native layer is the responsibility of the C++ implementation.
 *
 * <h2>Usage</h2>
 * <pre>
 *   TransformationPipeline pipeline = new TransformationPipeline();
 *   RawData      input  = new RawData("HEX", hexBytes);
 *   PipelineResult result = pipeline.execute(input);
 *   System.out.println(result);
 * </pre>
 */
public class TransformationPipeline {

    // ------------------------------------------------------------------ //
    //  Library bootstrap                                                   //
    // ------------------------------------------------------------------ //
    static {
        /*
         * Loads  libTransformationPipeline.so  (Linux)
         *         TransformationPipeline.dll   (Windows)
         *         libTransformationPipeline.dylib (macOS)
         *
         * Set -Djava.library.path=<dir> at JVM startup, or place the
         * library on the OS dynamic-linker search path.
         */
        System.loadLibrary("TransformationPipeline");
    }

    // ------------------------------------------------------------------ //
    //  Native method declarations                                          //
    // ------------------------------------------------------------------ //

    /**
     * Stage 1 — Read / interpret the low-level data format.
     *
     * <p>Takes the raw payload bytes together with a format tag and returns an
     * opaque intermediate representation (IR) as a byte array.  The IR format
     * is an internal contract between {@code nativeRead} and {@code nativeTransform};
     * Java code treats it as an opaque handle.
     *
     * @param format  format identifier string (e.g. {@code "HEX"}, {@code "BASE64"})
     * @param payload raw input bytes
     * @return opaque IR byte array; never {@code null}
     * @throws PipelineException (stage=READ) if the data cannot be interpreted
     */
    private native byte[] nativeRead(String format, byte[] payload);

    /**
     * Stage 2 — Apply transformation rules to the intermediate representation.
     *
     * <p>Consumes the IR produced by {@link #nativeRead} and applies a set of
     * predefined transformation rules (e.g. byte-order normalisation, field
     * remapping, checksum injection).  Returns a transformed IR.
     *
     * @param intermediateRepresentation opaque byte array from {@link #nativeRead}
     * @return transformed IR byte array; never {@code null}
     * @throws PipelineException (stage=TRANSFORM) if a rule cannot be applied
     */
    private native byte[] nativeTransform(byte[] intermediateRepresentation);

    /**
     * Stage 3 — Generate the final output from the transformed IR.
     *
     * <p>Serialises the transformed IR into a {@link PipelineResult}.  The C++
     * side constructs the object directly via JNI to keep the generated bytes
     * and metadata together.
     *
     * @param transformedData opaque byte array from {@link #nativeTransform}
     * @return fully populated {@link PipelineResult}; never {@code null}
     * @throws PipelineException (stage=GENERATE) if output cannot be produced
     */
    private native PipelineResult nativeGenerate(byte[] transformedData);

    // ------------------------------------------------------------------ //
    //  Public API                                                          //
    // ------------------------------------------------------------------ //

    /**
     * Executes the full three-stage data-transformation pipeline.
     *
     * <pre>
     *   RawData ──nativeRead──► IR ──nativeTransform──► IR' ──nativeGenerate──► PipelineResult
     * </pre>
     *
     * @param rawData structured input data; must not be {@code null}
     * @return the final {@link PipelineResult}
     * @throws IllegalArgumentException if {@code rawData} is {@code null}
     * @throws PipelineException        if any pipeline stage fails
     */
    public PipelineResult execute(RawData rawData) {
        if (rawData == null)
            throw new IllegalArgumentException("rawData must not be null");

        // Stage 1 – Read
        byte[] ir = nativeRead(rawData.getFormat(), rawData.getPayload());

        // Stage 2 – Transform
        byte[] transformedIr = nativeTransform(ir);

        // Stage 3 – Generate
        return nativeGenerate(transformedIr);
    }

    // ------------------------------------------------------------------ //
    //  Smoke-test entry point                                              //
    // ------------------------------------------------------------------ //
    public static void main(String[] args) {
        TransformationPipeline pipeline = new TransformationPipeline();

        // Simulate a tiny HEX-encoded input: bytes 0x01 0x02 0x03
        byte[] samplePayload = { 0x01, 0x02, 0x03, 0x04, 0x05 };
        RawData input = new RawData("HEX", samplePayload);

        System.out.println("Input  : " + input);

        PipelineResult result = pipeline.execute(input);

        System.out.println("Result : " + result);
        System.out.printf("  Output bytes (%d): ", result.getData().length);
        for (byte b : result.getData()) System.out.printf("%02X ", b);
        System.out.println();
    }
}