#include <jni.h>
#include <stdlib.h>
#include <string.h>
#include "NativeSerializer.h" // Generated by javac -h

// ----------------------------------------------------------------------------
// SERIALIZATION: Java Object -> C Byte Buffer -> jbyteArray
// ----------------------------------------------------------------------------
JNIEXPORT jbyteArray JNICALL Java_NativeSerializer_serialize
  (JNIEnv *env, jobject thisObj, jobject userData) {
    
    // 1. Get the class of UserData
    jclass userClass = (*env)->GetObjectClass(env, userData);

    // 2. Get Field IDs for id, name, and balance
    jfieldID idField = (*env)->GetFieldID(env, userClass, "id", "I");
    jfieldID balanceField = (*env)->GetFieldID(env, userClass, "balance", "D");
    jfieldID nameField = (*env)->GetFieldID(env, userClass, "name", "Ljava/lang/String;");

    // 3. Extract data from the Java Object
    jint id = (*env)->GetIntField(env, userData, idField);
    jdouble balance = (*env)->GetDoubleField(env, userData, balanceField);
    jstring nameStr = (jstring)(*env)->GetObjectField(env, userData, nameField);

    const char *nameChars = (*env)->GetStringUTFChars(env, nameStr, NULL);
    jint nameLength = (jint)strlen(nameChars);

    // 4. Calculate total buffer size: id(4) + balance(8) + nameLength(4) + nameBytes
    int totalSize = sizeof(jint) + sizeof(jdouble) + sizeof(jint) + nameLength;
    char *buffer = (char *)malloc(totalSize);

    // 5. Pack the data tightly into the binary buffer
    int offset = 0;
    memcpy(buffer + offset, &id, sizeof(jint));
    offset += sizeof(jint);
    
    memcpy(buffer + offset, &balance, sizeof(jdouble));
    offset += sizeof(jdouble);
    
    memcpy(buffer + offset, &nameLength, sizeof(jint));
    offset += sizeof(jint);
    
    memcpy(buffer + offset, nameChars, nameLength);

    // 6. Create a Java byte array and copy the C buffer into it
    jbyteArray result = (*env)->NewByteArray(env, totalSize);
    (*env)->SetByteArrayRegion(env, result, 0, totalSize, (jbyte *)buffer);

    // 7. Cleanup C memory
    (*env)->ReleaseStringUTFChars(env, nameStr, nameChars);
    free(buffer);

    return result;
}

// ----------------------------------------------------------------------------
// DESERIALIZATION: jbyteArray -> C Byte Buffer -> Java Object
// ----------------------------------------------------------------------------
JNIEXPORT jobject JNICALL Java_NativeSerializer_deserialize
  (JNIEnv *env, jobject thisObj, jbyteArray byteArray) {
    
    // 1. Get the raw bytes from Java
    jbyte *buffer = (*env)->GetByteArrayElements(env, byteArray, NULL);
    
    // 2. Unpack the variables from the binary buffer
    int offset = 0;
    
    jint id;
    memcpy(&id, buffer + offset, sizeof(jint));
    offset += sizeof(jint);
    
    jdouble balance;
    memcpy(&balance, buffer + offset, sizeof(jdouble));
    offset += sizeof(jdouble);
    
    jint nameLength;
    memcpy(&nameLength, buffer + offset, sizeof(jint));
    offset += sizeof(jint);
    
    // Allocate space for the string + null terminator
    char *nameChars = (char *)malloc(nameLength + 1);
    memcpy(nameChars, buffer + offset, nameLength);
    nameChars[nameLength] = '\0'; // Null-terminate the C string

    // 3. Convert C string back to Java String
    jstring nameStr = (*env)->NewStringUTF(env, nameChars);

    // 4. Find the UserData class and its constructor: (int, String, double)
    jclass userClass = (*env)->FindClass(env, "UserData");
    jmethodID constructor = (*env)->GetMethodID(env, userClass, "<init>", "(ILjava/lang/String;D)V");

    // 5. Instantiate a new UserData object
    jobject newUserObject = (*env)->NewObject(env, userClass, constructor, id, nameStr, balance);

    // 6. Cleanup C memory (JNI_ABORT means we don't need to copy changes back to Java)
    (*env)->ReleaseByteArrayElements(env, byteArray, buffer, JNI_ABORT);
    free(nameChars);

    return newUserObject;
}