#include <jni.h>
#include <iostream>
#include <cstring>
#include "UserAuthenticator.h" // Generated by javac -h

JNIEXPORT void JNICALL Java_UserAuthenticator_performNativeAuthentication(JNIEnv *env, jobject obj) {
    
    // 1. Get the class of the Java object
    jclass authClass = env->GetObjectClass(obj);

    // 2. Retrieve the 'username' String field from Java
    jfieldID userField = env->GetFieldID(authClass, "username", "Ljava/lang/String;");
    jstring jUsername = (jstring) env->GetObjectField(obj, userField);
    const char *cUsername = env->GetStringUTFChars(jUsername, nullptr);

    // 3. Retrieve the 'authToken' String field from Java
    jfieldID tokenField = env->GetFieldID(authClass, "authToken", "Ljava/lang/String;");
    jstring jToken = (jstring) env->GetObjectField(obj, tokenField);
    const char *cToken = env->GetStringUTFChars(jToken, nullptr);

    std::cout << "\n[C++] --- Native Auth Module Executing ---" << std::endl;
    std::cout << "[C++] Validating user : " << cUsername << std::endl;
    std::cout << "[C++] Provided token  : " << cToken << std::endl;

    // 4. Perform native authentication logic (mocked here)
    bool isAuthorized = false;
    int grantedLevel = 0;
    const char* logMessage = "";

    // Simulate secure token validation (e.g., checking against a PAM module or native DB)
    if (std::strcmp(cUsername, "admin_user") == 0 && std::strcmp(cToken, "secure_token_123") == 0) {
        isAuthorized = true;
        grantedLevel = 5; // Admin level
        logMessage = "SUCCESS - Identity verified natively.";
    } else {
        isAuthorized = false;
        grantedLevel = 0;
        logMessage = "FAILED - Invalid credentials or token.";
    }

    // 5. Write the results back to the Java object's fields
    
    // Update 'isAuthenticated' (boolean / JNI signature "Z")
    jfieldID isAuthField = env->GetFieldID(authClass, "isAuthenticated", "Z");
    env->SetBooleanField(obj, isAuthField, isAuthorized ? JNI_TRUE : JNI_FALSE);

    // Update 'accessLevel' (int / JNI signature "I")
    jfieldID accessLevelField = env->GetFieldID(authClass, "accessLevel", "I");
    env->SetIntField(obj, accessLevelField, grantedLevel);

    // 6. Invoke a Java callback method to log the result
    // JNI Signature "(Ljava/lang/String;)V" -> Takes a String, returns void
    jmethodID logMethod = env->GetMethodID(authClass, "logAuthAttempt", "(Ljava/lang/String;)V");
    if (logMethod != nullptr) {
        jstring jLogMsg = env->NewStringUTF(logMessage);
        env->CallVoidMethod(obj, logMethod, jLogMsg);
        env->DeleteLocalRef(jLogMsg);
    }

    std::cout << "[C++] --- Native Auth Module Finished ---\n" << std::endl;

    // 7. Cleanup memory allocated for C strings
    env->ReleaseStringUTFChars(jUsername, cUsername);
    env->ReleaseStringUTFChars(jToken, cToken);
    
    // Clean up local references
    env->DeleteLocalRef(jUsername);
    env->DeleteLocalRef(jToken);
    env->DeleteLocalRef(authClass);
}