#include <jni.h>
#include <iostream>
#include <string>
#include <sstream>
#include "JniInspector.h" // Generated by the Java compiler

extern "C"
JNIEXPORT jstring JNICALL Java_JniInspector_inspectObject(JNIEnv *env, jobject thisObj, jobject targetObj) {
    if (targetObj == nullptr) {
        return env->NewStringUTF("Object is null");
    }

    std::stringstream report;
    std::cout << "[C++] Inspecting object structure via JNI..." << std::endl;

    // 1. Get the class of the target object
    jclass targetClass = env->GetObjectClass(targetObj);

    // 2. Look up java.lang.Class and java.lang.reflect.Field to use Reflection via JNI
    jclass classType = env->FindClass("java/lang/Class");
    jclass fieldType = env->FindClass("java/lang/reflect/Field");

    // Get method IDs for Class.getName(), Class.getDeclaredFields(), and Field.getName()
    jmethodID getNameMid = env->GetMethodID(classType, "getName", "()Ljava/lang/String;");
    jmethodID getFieldsMid = env->GetMethodID(classType, "getDeclaredFields", "()[Ljava/lang/reflect/Field;");
    jmethodID fieldGetNameMid = env->GetMethodID(fieldType, "getName", "()Ljava/lang/String;");

    // 3. Extract and append the Class Name
    jstring classNameObj = (jstring) env->CallObjectMethod(targetClass, getNameMid);
    const char* classNameCStr = env->GetStringUTFChars(classNameObj, nullptr);
    report << "Class Name: " << classNameCStr << "\n";
    env->ReleaseStringUTFChars(classNameObj, classNameCStr);
    env->DeleteLocalRef(classNameObj);

    // 4. Extract the array of declared fields
    jobjectArray fieldsArray = (jobjectArray) env->CallObjectMethod(targetClass, getFieldsMid);
    jsize fieldCount = env->GetArrayLength(fieldsArray);
    
    report << "Number of Declared Fields: " << fieldCount << "\n";
    report << "Fields:\n";

    // 5. Iterate over the fields to inspect their names
    for (jsize i = 0; i < fieldCount; i++) {
        // Get the Field object from the array
        jobject fieldObj = env->GetObjectArrayElement(fieldsArray, i);
        
        // Call Field.getName()
        jstring fieldNameObj = (jstring) env->CallObjectMethod(fieldObj, fieldGetNameMid);
        const char* fieldNameCStr = env->GetStringUTFChars(fieldNameObj, nullptr);

        // Append to our C++ string stream report
        report << " - " << fieldNameCStr << "\n";

        // Free local memory resources to prevent leaks
        env->ReleaseStringUTFChars(fieldNameObj, fieldNameCStr);
        env->DeleteLocalRef(fieldNameObj);
        env->DeleteLocalRef(fieldObj);
    }

    // Free remaining local JNI references
    env->DeleteLocalRef(targetClass);
    env->DeleteLocalRef(classType);
    env->DeleteLocalRef(fieldType);
    env->DeleteLocalRef(fieldsArray);

    std::cout << "[C++] Inspection complete. Returning report to Java." << std::endl;

    // 6. Convert the C++ string report to a jstring and return to Java
    return env->NewStringUTF(report.str().c_str());
}