#include <jni.h>
#include <float.h> // For DBL_MAX
#include "NumericalAnalyzer.h" // Automatically generated by javac

/*
 * Class:     NumericalAnalyzer
 * Method:    analyze
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_NumericalAnalyzer_analyze(JNIEnv *env, jobject obj, jdoubleArray dataset) {
    if (dataset == NULL) {
        return NULL;
    }

    // 1. Get the length of the dataset
    jsize len = (*env)->GetArrayLength(env, dataset);
    if (len == 0) {
        return NULL; // Handle empty dataset
    }

    // 2. Obtain a pointer to the raw double array elements
    // This allows C to operate directly on the numerical data
    jdouble *elements = (*env)->GetDoubleArrayElements(env, dataset, NULL);
    if (elements == NULL) {
        return NULL; /* OutOfMemoryError already thrown by JVM */
    }

    // 3. Perform Analysis: Aggregation and Transformation
    double min = DBL_MAX;
    double max = -DBL_MAX;
    double sum = 0.0;

    // First pass: Calculate min, max, and sum
    for (int i = 0; i < len; i++) {
        double val = elements[i];
        if (val < min) min = val;
        if (val > max) max = val;
        sum += val;
    }

    // Calculate average
    double average = sum / len;

    // Second pass: Calculate population variance
    double variance_sum = 0.0;
    for (int i = 0; i < len; i++) {
        double diff = elements[i] - average;
        variance_sum += (diff * diff);
    }
    double variance = variance_sum / len;

    // 4. Release original array elements. 
    // JNI_ABORT is used because we only read the data and didn't modify the input array.
    (*env)->ReleaseDoubleArrayElements(env, dataset, elements, JNI_ABORT);

    // 5. Create a new Java double array to return the 5 statistical results
    jdoubleArray result = (*env)->NewDoubleArray(env, 5);
    if (result == NULL) {
        return NULL; /* OutOfMemoryError */
    }

    // 6. Populate the results buffer
    jdouble stats[5];
    stats[0] = min;
    stats[1] = max;
    stats[2] = sum;
    stats[3] = average;
    stats[4] = variance;

    // Copy the C array into the Java array
    (*env)->SetDoubleArrayRegion(env, result, 0, 5, stats);

    // 7. Return the analysis result to Java
    return result;
}