#include <jni.h>
#include <iostream>
#include "DynamicInvoker.h" // Generated by the Java compiler

extern "C"
JNIEXPORT jint JNICALL Java_DynamicInvoker_invokeMethodDynamically
  (JNIEnv *env, jobject thisObj, jobject mathOpsObj, jstring methodName, jint a, jint b) {

    // 1. Get the class of the passed Java object
    jclass mathClass = env->GetObjectClass(mathOpsObj);
    if (mathClass == nullptr) {
        std::cerr << "[C++] Error: Could not find MathOperations class." << std::endl;
        return -1;
    }

    // 2. Convert jstring (method name) to a standard C-style string
    const char *cMethodName = env->GetStringUTFChars(methodName, nullptr);

    // 3. Dynamically resolve the Method ID at runtime
    // The signature "(II)I" means the method takes two 'int' arguments and returns an 'int'
    jmethodID methodId = env->GetMethodID(mathClass, cMethodName, "(II)I");
    
    if (methodId == nullptr) {
        std::cerr << "[C++] Error: Could not find method named '" << cMethodName << "'." << std::endl;
        env->ReleaseStringUTFChars(methodName, cMethodName);
        return -1; // JNI will throw a NoSuchMethodError in Java natively
    }

    std::cout << "[C++] Dynamically found method '" << cMethodName << "'. Invoking it now..." << std::endl;

    // 4. Invoke the selected method from native code
    jint result = env->CallIntMethod(mathOpsObj, methodId, a, b);

    std::cout << "[C++] Method execution finished. Computed result: " << result << std::endl;

    // Release the string resource to avoid memory leaks
    env->ReleaseStringUTFChars(methodName, cMethodName);

    // 5. Return the result back to Java
    return result;
}