#include <jni.h>
#include <iostream>
#include "JniPropertyAccessor.h" // This will be generated by the Java compiler

extern "C"
JNIEXPORT jstring JNICALL Java_JniPropertyAccessor_getPersonName(JNIEnv *env, jobject thisObj, jobject personObj) {
    
    // 1. Get the class of the passed Java object
    jclass personClass = env->GetObjectClass(personObj);
    if (personClass == nullptr) {
        std::cerr << "[C++] Error: Could not find Person class." << std::endl;
        return nullptr;
    }

    // 2. Get the Field ID for the 'name' property
    // The signature "Ljava/lang/String;" specifies the property is a String
    jfieldID nameFieldId = env->GetFieldID(personClass, "name", "Ljava/lang/String;");
    if (nameFieldId == nullptr) {
        std::cerr << "[C++] Error: Could not find 'name' field." << std::endl;
        return nullptr;
    }

    // 3. Extract the object's property value using the Field ID
    jstring nameValue = (jstring) env->GetObjectField(personObj, nameFieldId);

    // (Optional) Prove we have accessed it in native code by printing it
    const char *cName = env->GetStringUTFChars(nameValue, nullptr);
    std::cout << "[C++] Native code successfully accessed the property value: " << cName << std::endl;
    env->ReleaseStringUTFChars(nameValue, cName);

    // 4. Return the extracted property value back to Java
    return nameValue;
}