/* Auto-generated by javac -h for the default-package class HardwareInfo */
#include <jni.h>

#ifndef _Included_HardwareInfo
#define _Included_HardwareInfo
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_HardwareInfo_getCpuModel(JNIEnv *, jobject);
JNIEXPORT jint    JNICALL Java_HardwareInfo_getCpuCores(JNIEnv *, jobject);
JNIEXPORT jint    JNICALL Java_HardwareInfo_getCpuLogicalProcessors(JNIEnv *, jobject);
JNIEXPORT jlong   JNICALL Java_HardwareInfo_getCpuFrequencyMHz(JNIEnv *, jobject);
JNIEXPORT jlong   JNICALL Java_HardwareInfo_getTotalMemoryBytes(JNIEnv *, jobject);
JNIEXPORT jlong   JNICALL Java_HardwareInfo_getFreeMemoryBytes(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_HardwareInfo_getOsName(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_HardwareInfo_getOsVersion(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_HardwareInfo_getOsArchitecture(JNIEnv *, jobject);
JNIEXPORT jlong   JNICALL Java_HardwareInfo_getTotalDiskBytes(JNIEnv *, jobject);
JNIEXPORT jlong   JNICALL Java_HardwareInfo_getFreeDiskBytes(JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_HardwareInfo_getHostname(JNIEnv *, jobject);
JNIEXPORT jlong   JNICALL Java_HardwareInfo_getUptimeSeconds(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif