#include <jni.h>
#include <iostream>

extern "C"
JNIEXPORT void JNICALL
Java_com_example_NativeCore_runPluginBehavior(JNIEnv *env, jobject thiz, jstring pluginName) {
    
    // 1. Find the PluginManager class
    jclass managerClass = env->FindClass("com/example/PluginManager");
    if (managerClass == nullptr) {
        std::cerr << "Failed to find PluginManager class." << std::endl;
        return;
    }

    // 2. Find the static 'getPlugin' method on PluginManager
    // Signature: takes a String (Ljava/lang/String;), returns an IPlugin (Lcom/example/IPlugin;)
    jmethodID getPluginMethod = env->GetStaticMethodID(
        managerClass, 
        "getPlugin", 
        "(Ljava/lang/String;)Lcom/example/IPlugin;"
    );

    if (getPluginMethod == nullptr) {
        std::cerr << "Failed to find getPlugin method." << std::endl;
        env->DeleteLocalRef(managerClass);
        return;
    }

    // 3. Call getPlugin() passing the pluginName requested by the user
    jobject pluginInstance = env->CallStaticObjectMethod(managerClass, getPluginMethod, pluginName);
    
    if (pluginInstance == nullptr) {
        // The Java map returned null (plugin not found)
        std::cerr << "Plugin not found in registry." << std::endl;
        env->DeleteLocalRef(managerClass);
        return;
    }

    // 4. Find the IPlugin interface class to locate the 'execute' method
    // In JNI, you can look up the interface class directly to call polymorphic methods
    jclass pluginInterfaceClass = env->FindClass("com/example/IPlugin");
    if (pluginInterfaceClass == nullptr) {
        std::cerr << "Failed to find IPlugin interface." << std::endl;
        env->DeleteLocalRef(pluginInstance);
        env->DeleteLocalRef(managerClass);
        return;
    }

    // 5. Find the 'execute' method on the IPlugin interface
    // Signature: takes a String (Ljava/lang/String;), returns void (V)
    jmethodID executeMethod = env->GetMethodID(
        pluginInterfaceClass, 
        "execute", 
        "(Ljava/lang/String;)V"
    );

    if (executeMethod != nullptr) {
        // 6. Prepare data generated by the native C++ logic to pass to the plugin
        jstring jPayload = env->NewStringUTF("Data generated from C++ Core Engine");

        // 7. Invoke the plugin's execute method!
        env->CallVoidMethod(pluginInstance, executeMethod, jPayload);

        // Clean up the payload string
        env->DeleteLocalRef(jPayload);
    } else {
        std::cerr << "Failed to find execute method on IPlugin." << std::endl;
    }

    // 8. Clean up local references
    env->DeleteLocalRef(pluginInterfaceClass);
    env->DeleteLocalRef(pluginInstance);
    env->DeleteLocalRef(managerClass);
}