#include <jni.h>
#include <stdint.h>
#include <string.h>
#include "SensorDecoder.h" // Automatically generated by javac

/*
 * Class:     SensorDecoder
 * Method:    decodeStream
 * Signature: ([B)[LSensorDecoder$SensorReading;
 */
JNIEXPORT jobjectArray JNICALL Java_SensorDecoder_decodeStream(JNIEnv *env, jobject obj, jbyteArray stream) {
    if (stream == NULL) {
        return NULL;
    }

    // 1. Get the stream size and calculate the number of packets
    jsize len = (*env)->GetArrayLength(env, stream);
    int packet_size = 9;
    
    if (len % packet_size != 0) {
        // Stream length must be a multiple of the packet size
        return NULL; 
    }
    
    int num_records = len / packet_size;

    // 2. Locate the Java class and constructor for SensorReading
    jclass readingClass = (*env)->FindClass(env, "SensorDecoder$SensorReading");
    if (readingClass == NULL) return NULL;

    jmethodID constructor = (*env)->GetMethodID(env, readingClass, "<init>", "(IIF)V");
    if (constructor == NULL) return NULL;

    // 3. Create the destination object array to return to Java
    jobjectArray resultArray = (*env)->NewObjectArray(env, num_records, readingClass, NULL);
    if (resultArray == NULL) return NULL;

    // 4. Pin the primitive byte array to read its contents
    jbyte *bytes = (*env)->GetByteArrayElements(env, stream, NULL);
    if (bytes == NULL) return NULL;

    // 5. Interpret and decode the stream
    for (int i = 0; i < num_records; i++) {
        int offset = i * packet_size;

        // Decode Sensor ID (1 byte, unsigned)
        int sensorId = (unsigned char)bytes[offset];

        // Decode Timestamp (4 bytes, Little-Endian)
        uint32_t ts_int = ((unsigned char)bytes[offset + 1]) |
                          ((unsigned char)bytes[offset + 2] << 8) |
                          ((unsigned char)bytes[offset + 3] << 16) |
                          ((unsigned char)bytes[offset + 4] << 24);

        // Decode Value (4 bytes, Little-Endian Float)
        uint32_t val_int = ((unsigned char)bytes[offset + 5]) |
                           ((unsigned char)bytes[offset + 6] << 8) |
                           ((unsigned char)bytes[offset + 7] << 16) |
                           ((unsigned char)bytes[offset + 8] << 24);

        // Safely copy the integer representation of the bytes into a float variable
        float value;
        memcpy(&value, &val_int, sizeof(float));

        // Instantiate the Java Object for this record
        jobject readingObj = (*env)->NewObject(env, readingClass, constructor, sensorId, (jint)ts_int, (jfloat)value);
        
        // Add the object to the result array
        (*env)->SetObjectArrayElement(env, resultArray, i, readingObj);
        
        // Delete the local reference to prevent memory leaks during large stream processing
        (*env)->DeleteLocalRef(env, readingObj);
    }

    // 6. Release the byte array memory (JNI_ABORT means we didn't modify the original array)
    (*env)->ReleaseByteArrayElements(env, stream, bytes, JNI_ABORT);

    // 7. Return the structured, decoded result to Java
    return resultArray;
}