/* DO NOT EDIT — generated by: javac -h . LogAnalyzer.java */
#include <jni.h>

#ifndef _Included_com_example_loganalyzer_LogAnalyzer
#define _Included_com_example_loganalyzer_LogAnalyzer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL
Java_com_example_loganalyzer_LogAnalyzer_analyzeBatch(
        JNIEnv *env,
        jobject  thiz,
        jobjectArray events);

#ifdef __cplusplus
}
#endif
#endif