#include <jni.h>
#include <stdlib.h>
#include "PayloadProcessor.h" // Generated by javac

/*
 * Class:     PayloadProcessor
 * Method:    processPayload
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_PayloadProcessor_processPayload(JNIEnv *env, jobject obj, jbyteArray payload) {
    if (payload == NULL) {
        return NULL;
    }

    // 1. Get the length of the incoming binary payload
    jsize len = (*env)->GetArrayLength(env, payload);

    // 2. Obtain a pointer to the raw byte array elements
    // This pins the array or copies it so C can read the contents safely
    jbyte *body = (*env)->GetByteArrayElements(env, payload, NULL);
    if (body == NULL) {
        return NULL; /* JVM already threw OutOfMemoryError */
    }

    // 3. Create a new Java byte array to hold the result
    jbyteArray result = (*env)->NewByteArray(env, len);
    if (result == NULL) {
        (*env)->ReleaseByteArrayElements(env, payload, body, JNI_ABORT);
        return NULL; /* OutOfMemoryError */
    }

    // 4. Allocate a temporary C buffer for the transformed data
    jbyte *transformed = (jbyte *)malloc(len * sizeof(jbyte));
    if (transformed == NULL) {
        (*env)->ReleaseByteArrayElements(env, payload, body, JNI_ABORT);
        return NULL;
    }

    // 5. Inspect and transform the binary data
    // Here we apply a bitwise NOT (~) operation to invert all bits
    for (int i = 0; i < len; i++) {
        transformed[i] = ~body[i]; 
    }

    // 6. Copy the transformed C buffer into the newly created Java byte array
    (*env)->SetByteArrayRegion(env, result, 0, len, transformed);

    // 7. Clean up memory allocations
    free(transformed);
    
    // Release original array elements. We use JNI_ABORT because we didn't 
    // modify the original array and don't need to copy changes back to Java.
    (*env)->ReleaseByteArrayElements(env, payload, body, JNI_ABORT);

    // 8. Return the processed payload to Java
    return result;
}