#include <jni.h>
#include <iostream>
#include "Device.h" // The header generated by javac -h

// The function signature matches the one generated in Device.h
JNIEXPORT void JNICALL Java_Device_processDeviceOperation(JNIEnv *env, jobject obj) {
    
    // 1. Get the class of the Java object that invoked this method
    jclass deviceClass = env->GetObjectClass(obj);

    // 2. Retrieve a primitive field directly (e.g., 'id' of type 'int' / JNI signature "I")
    jfieldID idField = env->GetFieldID(deviceClass, "id", "I");
    if (idField == nullptr) return; // Field not found
    jint deviceId = env->GetIntField(obj, idField);

    // 3. Retrieve a boolean field directly (e.g., 'isActive' of type 'boolean' / JNI signature "Z")
    jfieldID isActiveField = env->GetFieldID(deviceClass, "isActive", "Z");
    if (isActiveField == nullptr) return;
    jboolean isActive = env->GetBooleanField(obj, isActiveField);

    // 4. Call a Java method to get an object (e.g., 'getName()' returning a String)
    // JNI Signature "()Ljava/lang/String;" means: takes no arguments (), returns a String
    jmethodID getNameMethod = env->GetMethodID(deviceClass, "getName", "()Ljava/lang/String;");
    if (getNameMethod == nullptr) return; 
    
    // Call the method, which returns a Java String object
    jstring jName = (jstring) env->CallObjectMethod(obj, getNameMethod);

    // Convert the Java String (jstring) into a C/C++ style string (const char*)
    const char *cName = env->GetStringUTFChars(jName, nullptr);

    // --- START NATIVE C++ DEVICE LOGIC ---
    std::cout << "\n[C++] --- Native Device Processor Started ---" << std::endl;
    std::cout << "[C++] Device ID   : " << deviceId << std::endl;
    std::cout << "[C++] Device Name : " << cName << std::endl;
    std::cout << "[C++] Status      : " << (isActive ? "Active" : "Inactive") << std::endl;

    if (isActive) {
        std::cout << "[C++] Performing low-level hardware communication for " << cName << "..." << std::endl;
        // ... Native device code (e.g., hardware polling, memory mapped I/O, ioctl) goes here ...
    } else {
        std::cout << "[C++] Device is offline. Aborting operations." << std::endl;
    }
    std::cout << "[C++] ---------------------------------------\n" << std::endl;
    // --- END NATIVE C++ DEVICE LOGIC ---

    // 5. Cleanup memory and references
    // Release the memory allocated for the C string
    env->ReleaseStringUTFChars(jName, cName);
    
    // Delete the local reference to the class
    env->DeleteLocalRef(deviceClass);
}