#include <jni.h>
#include "HardwareInfo.h" // Automatically generated by javac -h

// Include OS-specific headers for hardware access
#ifdef _WIN32
    #include <windows.h>
#else
    #include <unistd.h>
#endif

/*
 * Class:     HardwareInfo
 * Method:    getCpuCores
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_HardwareInfo_getCpuCores(JNIEnv *env, jobject thisObj) {
#ifdef _WIN32
    SYSTEM_INFO sysinfo;
    GetSystemInfo(&sysinfo);
    return (jint) sysinfo.dwNumberOfProcessors;
#else
    // POSIX standard for Linux/macOS
    return (jint) sysconf(_SC_NPROCESSORS_ONLN);
#endif
}

/*
 * Class:     HardwareInfo
 * Method:    getTotalRam
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_HardwareInfo_getTotalRam(JNIEnv *env, jobject thisObj) {
#ifdef _WIN32
    MEMORYSTATUSEX status;
    status.dwLength = sizeof(status);
    GlobalMemoryStatusEx(&status);
    return (jlong) status.ullTotalPhys;
#else
    // POSIX standard: multiply the number of physical pages by the size of a page
    long pages = sysconf(_SC_PHYS_PAGES);
    long page_size = sysconf(_SC_PAGE_SIZE);
    
    // Cast to long long before multiplying to prevent integer overflow on modern systems with high RAM
    return (jlong) ((long long)pages * (long long)page_size);
#endif
}