#include <jni.h>
#include "ImageFilter.h" // This will be generated by javac

// Implementation of the native applyGrayscale method
JNIEXPORT void JNICALL Java_ImageFilter_applyGrayscale
  (JNIEnv *env, jobject obj, jintArray pixelsArray, jint width, jint height) {

    // 1. Get the length of the pixel array
    jsize length = (*env)->GetArrayLength(env, pixelsArray);

    // 2. Obtain a pointer to the array elements directly from JVM memory
    jint *pixels = (*env)->GetIntArrayElements(env, pixelsArray, 0);

    if (pixels == NULL) {
        return; // Out of memory exception thrown by JVM
    }

    // 3. Process the image array
    for (int i = 0; i < length; i++) {
        jint argb = pixels[i];

        // Extract the Alpha, Red, Green, and Blue channels using bit-shifting
        int a = (argb >> 24) & 0xFF;
        int r = (argb >> 16) & 0xFF;
        int g = (argb >> 8) & 0xFF;
        int b = argb & 0xFF;

        // Calculate Grayscale using the luminance formula (human eye weights)
        int gray = (int)(0.299 * r + 0.587 * g + 0.114 * b);

        // Repack the channels back into ARGB format
        pixels[i] = (a << 24) | (gray << 16) | (gray << 8) | gray;
    }

    // 4. Release the array elements. 
    // The '0' mode flag tells JNI to copy the updated C array back to the Java array.
    (*env)->ReleaseIntArrayElements(env, pixelsArray, pixels, 0);
}