#include <jni.h>
#include <stdlib.h>
#include "ImageEncoder.h" // Automatically generated by javac -h

/*
 * Class:     ImageEncoder
 * Method:    encodeImage
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ImageEncoder_encodeImage
  (JNIEnv *env, jobject thisObj, jbyteArray rawPixels, jint width, jint height) {

    // 1. Get the length of the input image array
    jsize len = (*env)->GetArrayLength(env, rawPixels);

    // 2. Obtain a pointer to the input elements in native memory
    jbyte *pixels = (*env)->GetByteArrayElements(env, rawPixels, NULL);

    // 3. Allocate a temporary buffer for the encoded data
    // In the worst case for RLE, the size could be 2 * len
    jbyte *encodedBuffer = (jbyte *)malloc(2 * len * sizeof(jbyte));
    if (encodedBuffer == NULL) {
        return NULL; // Handle memory allocation failure
    }
    
    int encodedSize = 0;

    // 4. Perform Run-Length Encoding (RLE)
    if (len > 0) {
        int count = 1;
        jbyte currentPixel = pixels[0];

        for (int i = 1; i < len; i++) {
            // If the pixel is identical and count hasn't exceeded a byte's max value (127)
            if (pixels[i] == currentPixel && count < 127) {
                count++;
            } else {
                // Write the count and the pixel value to our encoded buffer
                encodedBuffer[encodedSize++] = (jbyte)count;
                encodedBuffer[encodedSize++] = currentPixel;
                
                // Reset for the next run
                currentPixel = pixels[i];
                count = 1;
            }
        }
        // Write the final run
        encodedBuffer[encodedSize++] = (jbyte)count;
        encodedBuffer[encodedSize++] = currentPixel;
    }

    // 5. Release the input array elements (JNI_ABORT means we didn't alter the original Java array)
    (*env)->ReleaseByteArrayElements(env, rawPixels, pixels, JNI_ABORT);

    // 6. Create a new byte array in the JVM for our resulting encoded data
    jbyteArray result = (*env)->NewByteArray(env, encodedSize);

    // 7. Copy our native encoded buffer into the Java result array
    (*env)->SetByteArrayRegion(env, result, 0, encodedSize, encodedBuffer);

    // 8. Free the native temporary buffer
    free(encodedBuffer);

    // 9. Return the encoded image array back to Java
    return result;
}