/*
 * TextNormalizer.c
 *
 * JNI implementation of TextNormalizer.normalizeText().
 *
 * Normalization pipeline (per value):
 *   Step 1 — Convert jstring → UTF-8 C string.
 *   Step 2 — Trim leading and trailing ASCII whitespace.
 *   Step 3 — Collapse internal whitespace runs to a single space.
 *   Step 4 — Convert ASCII letters to lower-case (locale-independent).
 *   Step 5 — Convert the cleaned C string back to a jstring (UTF-8).
 *
 * Compile flags expected:
 *   -I${JAVA_HOME}/include -I${JAVA_HOME}/include/<platform>
 */

#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/* ------------------------------------------------------------------ */
/* Helper: lower-case a single ASCII byte (leaves non-ASCII untouched) */
/* ------------------------------------------------------------------ */
static unsigned char ascii_tolower(unsigned char c) {
    return (c >= 'A' && c <= 'Z') ? (unsigned char)(c + 32) : c;
}

/* ------------------------------------------------------------------ */
/* Helper: return 1 if byte is ASCII whitespace                        */
/* ------------------------------------------------------------------ */
static int is_ascii_space(unsigned char c) {
    /* space, tab, newline, carriage-return, form-feed, vertical-tab */
    return (c == ' ' || c == '\t' || c == '\n' ||
            c == '\r' || c == '\f' || c == '\v');
}

/* ------------------------------------------------------------------ */
/* normalize_utf8                                                       */
/*                                                                      */
/* Applies the full normalization pipeline to a NUL-terminated UTF-8   */
/* string.  Returns a newly malloc'd, NUL-terminated string; caller    */
/* must free() it.  Returns NULL on allocation failure.                 */
/* ------------------------------------------------------------------ */
static char *normalize_utf8(const char *src) {
    if (!src) return NULL;

    size_t len = strlen(src);

    /* Allocate output buffer — worst case same length as input + NUL */
    char *out = (char *)malloc(len + 1);
    if (!out) return NULL;

    const unsigned char *p   = (const unsigned char *)src;
    const unsigned char *end = p + len;

    /* ---- Step 1: skip leading ASCII whitespace ---- */
    while (p < end && is_ascii_space(*p)) {
        p++;
    }

    /* ---- Step 2: skip trailing ASCII whitespace ---- */
    while (end > p && is_ascii_space(*(end - 1))) {
        end--;
    }

    /* ---- Step 3 + 4: collapse internal spaces and lower-case ---- */
    size_t out_len = 0;
    int    in_ws   = 0;   /* are we currently inside a whitespace run? */

    while (p < end) {
        unsigned char c = *p;

        if (is_ascii_space(c)) {
            /*
             * Whitespace inside the trimmed range:
             * emit one space (when we first encounter the run),
             * then skip the rest of the run.
             */
            if (!in_ws) {
                out[out_len++] = ' ';
                in_ws = 1;
            }
            p++;
        } else {
            in_ws = 0;

            /*
             * ASCII letter → lower-case.
             * Multi-byte UTF-8 sequences (high bit set) are copied
             * verbatim — they are already encoded correctly.
             */
            if (c < 0x80) {
                /* ASCII byte */
                out[out_len++] = (char)ascii_tolower(c);
                p++;
            } else {
                /*
                 * Multi-byte UTF-8 sequence.
                 * Determine sequence length from the leading byte:
                 *   110xxxxx → 2 bytes
                 *   1110xxxx → 3 bytes
                 *   11110xxx → 4 bytes
                 *
                 * We copy the whole sequence unchanged; if it is
                 * malformed we still copy it (best-effort).
                 */
                int seq_len;
                if      ((c & 0xE0) == 0xC0) seq_len = 2;
                else if ((c & 0xF0) == 0xE0) seq_len = 3;
                else if ((c & 0xF8) == 0xF0) seq_len = 4;
                else                          seq_len = 1; /* invalid lead byte */

                /* Guard against reading past the buffer */
                if (p + seq_len > end) {
                    seq_len = (int)(end - p);
                }

                memcpy(out + out_len, p, (size_t)seq_len);
                out_len += (size_t)seq_len;
                p       += seq_len;
            }
        }
    }

    out[out_len] = '\0';
    return out;
}

/* ------------------------------------------------------------------ */
/* JNI entry point                                                      */
/*                                                                      */
/* Signature generated by:                                              */
/*   javac -h include src/TextNormalizer.java                           */
/*                                                                      */
/* Java method:                                                         */
/*   public native String normalizeText(String rawText);                */
/* ------------------------------------------------------------------ */
JNIEXPORT jstring JNICALL
Java_TextNormalizer_normalizeText(JNIEnv *env, jobject obj, jstring rawText) {

    /* ---- Guard: handle null from Java ---- */
    if (rawText == NULL) {
        return (*env)->NewStringUTF(env, "");
    }

    /* ---- Step A: obtain a UTF-8 C string from the jstring ---- */
    const char *utfChars = (*env)->GetStringUTFChars(env, rawText, NULL);
    if (utfChars == NULL) {
        /* OutOfMemoryError already pending */
        return NULL;
    }

    /* ---- Step B: run the normalization pipeline ---- */
    char *normalized = normalize_utf8(utfChars);

    /* Release the JNI-managed buffer as soon as we are done with it */
    (*env)->ReleaseStringUTFChars(env, rawText, utfChars);

    if (normalized == NULL) {
        /* malloc failed — throw OOM and return NULL */
        (*env)->ThrowNew(env,
            (*env)->FindClass(env, "java/lang/OutOfMemoryError"),
            "normalize_utf8: malloc failed");
        return NULL;
    }

    /* ---- Step C: build a new jstring from the normalized UTF-8 ---- */
    jstring result = (*env)->NewStringUTF(env, normalized);

    free(normalized);

    return result;
}