#include <jni.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include "TextNormalizer.h" // Automatically generated by javac

/*
 * Class:     TextNormalizer
 * Method:    normalize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TextNormalizer_normalize(JNIEnv *env, jobject obj, jstring input) {
    if (input == NULL) {
        return NULL;
    }

    // 1. Get the UTF-8 encoded string from Java
    const char *c_str = (*env)->GetStringUTFChars(env, input, NULL);
    if (c_str == NULL) {
        return NULL; /* OutOfMemoryError already thrown by JVM */
    }

    // 2. Perform normalization: Calculate trimming boundaries
    int len = strlen(c_str);
    int start = 0;
    int end = len - 1;

    // Find first non-whitespace character
    while (start < len && isspace((unsigned char)c_str[start])) {
        start++;
    }

    // Find last non-whitespace character
    while (end >= start && isspace((unsigned char)c_str[end])) {
        end--;
    }

    // 3. Allocate memory for the normalized text
    int new_len = end - start + 1;
    char *normalized_str = (char *)malloc(new_len + 1);
    
    if (normalized_str == NULL) {
        (*env)->ReleaseStringUTFChars(env, input, c_str);
        return NULL; /* Memory allocation failed */
    }

    // 4. Perform normalization: Copy trimmed string and apply case transformation (lowercase)
    for (int i = 0; i < new_len; i++) {
        normalized_str[i] = tolower((unsigned char)c_str[start + i]);
    }
    normalized_str[new_len] = '\0'; /* Null-terminate the string */

    // 5. Adapt back to Java: Create a new JNI String to return
    jstring result = (*env)->NewStringUTF(env, normalized_str);

    // 6. Clean up memory to prevent leaks
    free(normalized_str);
    (*env)->ReleaseStringUTFChars(env, input, c_str);

    // Return the normalized result back to Java
    return result;
}